# Generated by Django 4.2.7 on 2023-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0002_classmate_address_classmate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='classmate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=200),
        ),
    ]
