# Generated by Django 4.2.7 on 2023-11-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0004_alter_classmate_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='age',
            field=models.IntegerField(),
        ),
    ]
